baseURL = "https://makostin.github.io/fauna/"

relativeURLs = false
canonifyURLs = false

defaultContentLanguage = "ru"
defaultContentLanguageInSubdir = false

[languages]

[languages.ru]
title = "Стрекозы Беларуси"
languageCode = "ru"
label = "Русский"
weight = 1

[languages.en]
title = "Dragonflies of Belarus"
languageCode = "en"
label = "English"
weight = 2